# [ General settings ] #

title: OgGhostJelly's Hangout
description: A cool website for cool people.

domain: ogghostjelly.github.io
url: https://ogghostjelly.github.io

twitter_username: ogghostjelly
github_username:  ogghostjelly


# [ Structural settings ] #

collections:
  recipes:
    output: true
    permalink: cooking-with-ogghostjelly/:title
  navigators:
    output: true
    permalink: /:title

defaults:
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"
  - scope:
      path: ""
      type: "navigators"
    values:
      layout: "navigator"


# [ Build settings ] #

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
